### ISSUE TITLE
预计什么时候支持docx？另外建议提供根据token下载功能

### ISSUE THREAD

**Issue by rovertang** [jiegec/feishu-backup#1]
如题，现在看是不支持docx的，无法导出docx文件。
另外，如果提供一个根据token下载就更好了，运行的时候让用户输入token或者网址吧，然后就可以把这个飞书文档下下来，避免下载全部内容。
谢谢

**Comment by jiegec** [comment]
> 如题，现在看是不支持docx的，无法导出docx文件。 

你指的是导出功能吗？即保存一个 docx 文件到本地。

> 另外，如果提供一个根据token下载就更好了，运行的时候让用户输入token或者网址吧，然后就可以把这个飞书文档下下来，避免下载全部内容。 谢谢

在最新的 commit 里实现了。

**Comment by rovertang** [comment]
你指的是导出功能吗？即保存一个 docx 文件到本地。----------------对的。从打印出的内容看，有提示type=docx，但没有保存到本地。而docs的type，是可以导出的，并且下载了图片文件。
在最新的 commit 里实现了。---------23小时前更新了，给力啊。我试试看。

**Comment by jiegec** [comment]
> 你指的是导出功能吗？即保存一个 docx 文件到本地。----------------对的。从打印出的内容看，有提示type=docx，但没有保存到本地。而docs的type，是可以导出的，并且下载了图片文件。 在最新的 commit 里实现了。---------23小时前更新了，给力啊。我试试看。

我写这个项目的初衷是要导出 markdown，然后用 git 来管理 markdown，所以就没有做导出 docx 功能。

**Comment by rovertang** [comment]
我写这个项目的初衷是要导出 markdown，然后用 git 来管理 markdown，所以就没有做导出 docx 功能。
---------不不不，这个理解岔了。是飞书的文档，原来是1.0格式，称之为docs，现在是2.0格式，称之为docx。URL中也可以看出具体的区分。
我跑脚本是有下载老的URL中带有docs的飞书文档，但新的带docx的URL文档，只提示type=docx就没有下载具体的文件了。

**Comment by jiegec** [comment]
> 我写这个项目的初衷是要导出 markdown，然后用 git 来管理 markdown，所以就没有做导出 docx 功能。 ---------不不不，这个理解岔了。是飞书的文档，原来是1.0格式，称之为docs，现在是2.0格式，称之为docx。URL中也可以看出具体的区分。 我跑脚本是有下载老的URL中带有docs的飞书文档，但新的带docx的URL文档，只提示type=docx就没有下载具体的文件了。

ok，我理解了，飞书的命名有点误导人。。我看看怎么把我的文档迁移到 docx，再改改代码。

**Comment by rovertang** [comment]
> 
感谢。截取一下提示信息：
Downloading /xxxxxxxxxxx.md
Unsupported type: docx

其他问题我稍后补充一下。

**Comment by jiegec** [comment]
我发现我还没有新版文档的入口，只能创建旧的。

**Comment by rovertang** [comment]
> 我发现我还没有新版文档的入口，只能创建旧的。

![image](https://user-images.githubusercontent.com/1571397/177191741-984a3406-32f9-4eba-abc2-94811e49234c.png)
如图，默认是新的docx，下面还有旧版docs。

**Comment by rovertang** [comment]
补充一下新功能的测试：
运行命令：python backup.py --only doccnzhQfGPrImO9CU588YQ7aae
运行后找到了该文档，但该文档提示skipping：
Skipping /xxxxxxxxx.md: token nodcnxXiSIcHv4c1jHxommd321g not matching
也就是说：我通过打开URL获得的文档token，和代码里获得的文档token不一样。这个不是很理解为什么会不一样。

**Comment by jiegec** [comment]
> > 我发现我还没有新版文档的入口，只能创建旧的。
> 
> ![image](https://user-images.githubusercontent.com/1571397/177191741-984a3406-32f9-4eba-abc2-94811e49234c.png) 如图，默认是新的docx，下面还有旧版docs。

我的界面不一样，只有旧版的。

**Comment by rovertang** [comment]
> > > 我发现我还没有新版文档的入口，只能创建旧的。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/1571397/177191741-984a3406-32f9-4eba-abc2-94811e49234c.png) 如图，默认是新的docx，下面还有旧版docs。
> 
> 我的界面不一样，只有旧版的。

见：https://www.feishu.cn/hc/zh-CN/articles/981959499144
以下内容仅适用于新版文档，[点击这里](https://www.feishu.cn/hc/zh-CN/articles/563239506374)查看如何区分新旧版本文档。新版文档采用了分批逐步上线的策略，其中混合部署租户、专版未升级到 5.10 版本的租户、部分需接入新版文档 Open API 的租户，部分依赖 Jira Filter（问题筛选器）/页面关系图/ 翻译支持显示原文译文功能的租户暂不参与新版文档的第一批上线，如有疑问请咨询[飞书客服](https://feishu.cn/messenger/?route=start_helpdesk)。

看上去：1、试试升级飞书版本，PC端的也可以登录升级看看；2、咨询飞书客服来升级。
试试看吧。

**Comment by jiegec** [comment]
在和客服反馈以后，现在终于有新版文档的入口了。让我来看看怎么弄。

**Comment by jiegec** [comment]
已经实现。
